### PR TITLE
Keep dependencies the same version

### PR DESCRIPTION
**Pull request by peternied**

### CODE REVIEW

**Comment by peternied** [comment]
Thanks for the pull request, I would like to keep the downstream dependencies to the versions that I've already vetted, if you accept this change, I'll be happy to merge it into onedrive:master

**Comment by jlelse** [comment]
I don't understand what you exactly mean?

**Comment by peternied** [comment]
I don't want to change the version of retrofit, okhttp, or joda time that this project consumes

**Comment by jlelse** [comment]
ok

**Pull request merged**
